### PR TITLE
Add retry_delay

### PR DESCRIPTION
**Pull request by saschat**
Adds a retry_delay, fixing #110

Piggybacked is a fix for a failover bug.

See individual commits.

### CODE REVIEW

**Comment by saschat** [comment]
It seems I need to fix some tests...

**Comment by saschat** [comment]
Ok, ready now. Ignore the failed travis check. It fails to build microtime on iojs. I filed a bug report here: https://github.com/wadey/node-microtime/issues/58

**Comment by saschat** [comment]
I think the iojs build was broken here: https://github.com/memcachier/memjs/commit/a3966fe91fc4a8640b7da1e197e07f9fb131d5e1

Based on the microtime developer the problem probably lies with `prebuild-install`, saying it no longer supports iojs. Maybe we should remove it from travis?

**Comment by alevy** [comment]
Removing iojs from travis seems fine

**Pull request merged**
